# Generated by Django 5.2.17 on 2026-09-28 06:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('resources', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDeadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('due_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('snoozed', 'Snoozed'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=16)),
                ('source', models.CharField(choices=[('frontmatter', 'Frontmatter'), ('inline', 'Inline text'), ('manual', 'Manual')], default='inline', max_length=16)),
                ('confidence', models.IntegerField(default=50)),
                ('context', models.TextField(blank=True)),
                ('source_ref', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='documents.document')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='workspaces.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='resources.resource')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'deadlines_knowledge_deadline',
                'ordering': ['due_date', 'title'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='deadlines_k_status_bd6e0e_idx'), models.Index(fields=['workspace', 'due_date'], name='deadlines_k_workspa_fcdf75_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'due_date', 'title', 'source'), name='uniq_deadline_per_document')],
            },
        ),
    ]
