# Generated by Django 5.2.17 on 2026-09-25 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeyscope',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.project'),
        ),
        migrations.AddField(
            model_name='apikeyscope',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace'),
        ),
        migrations.AddConstraint(
            model_name='apikeyscope',
            constraint=models.UniqueConstraint(fields=('api_key', 'workspace', 'project', 'permission'), name='uniq_api_key_scope'),
        ),
    ]
