# Generated by Django 5.2.17 on 2026-10-04 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_oidc_issuer_user_oidc_subject_and_more'),
        ('resources', '0002_resource_no_takeover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeyscope',
            name='project',
            field=models.ForeignKey(blank=True, help_text="The project's Resource. A Project row and its Resource carry the same UUID, so existing values are unchanged; pointing at the Resource also means a scope keeps narrowing by that id when the project becomes a plain folder node in the tree.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='resources.resource'),
        ),
    ]
