# Generated by Django 5.2.17 on 2026-10-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_apikeyscope_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='budget_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='budget_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apikey',
            name='budget_window_seconds',
            field=models.PositiveIntegerField(default=86400),
        ),
        migrations.AddField(
            model_name='apikey',
            name='request_budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
