# Generated by Django 5.2.17 on 2026-09-25 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='scheduler', max_length=50, unique=True)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('boot_id', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'jobs_scheduler_state',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('task_key', models.CharField(db_index=True, max_length=100)),
                ('schedule_kind', models.CharField(choices=[('interval', 'Interval'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='interval', max_length=16)),
                ('schedule_config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('timeout_sec', models.IntegerField(blank=True, null=True)),
                ('max_retries', models.IntegerField(default=0)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jobs_job',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['enabled', 'next_run_at'], name='jobs_job_enabled_1fb7a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('task_key', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=16)),
                ('trigger', models.CharField(choices=[('schedule', 'Schedule'), ('manual', 'Manual'), ('system', 'System'), ('retry', 'Retry')], default='system', max_length=16)),
                ('attempt', models.IntegerField(default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('worker', models.CharField(blank=True, max_length=100)),
                ('error', models.TextField(blank=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='jobs.job')),
            ],
            options={
                'db_table': 'jobs_job_run',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='jobs_job_ru_status_b8c526_idx'), models.Index(fields=['task_key', 'status'], name='jobs_job_ru_task_ke_413bea_idx')],
            },
        ),
    ]
