# Generated by Django 5.2.17 on 2026-09-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_seed_default_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='exhausted',
            field=models.BooleanField(default=False, help_text="Set for one-shot ('once') jobs after they have fired."),
        ),
        migrations.AlterField(
            model_name='job',
            name='schedule_kind',
            field=models.CharField(choices=[('once', 'Once'), ('interval', 'Interval'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('cron', 'Cron')], default='interval', max_length=16),
        ),
    ]
