# Generated by Django 5.2.17 on 2026-09-25 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('workspace', 'Workspace'), ('project', 'Project'), ('document', 'Document'), ('file', 'File'), ('git_repository', 'Git repository'), ('secret', 'Secret'), ('mcp_server', 'MCP server'), ('api_key', 'API key')], db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resources', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='resources.resource')),
            ],
            options={
                'db_table': 'resources_resource',
                'ordering': ['resource_type', 'name'],
                'indexes': [models.Index(fields=['resource_type', 'name'], name='resources_r_resourc_6188ee_idx')],
            },
        ),
    ]
