# Generated by Django 5.2.17 on 2026-10-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_no_takeover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('workspace', 'Workspace'), ('project', 'Project'), ('folder', 'Folder'), ('document', 'Document'), ('file', 'File'), ('git_repository', 'Git repository'), ('secret', 'Secret'), ('mcp_server', 'MCP server'), ('gateway', 'Gateway target'), ('api_key', 'API key')], db_index=True, max_length=32),
        ),
    ]
