# Generated by Django 5.2.17 on 2026-09-25 12:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepository',
            fields=[
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='git_repository', serialize=False, to='resources.resource')),
                ('name', models.CharField(max_length=255)),
                ('remote_url', models.CharField(blank=True, max_length=1024)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('workflow', models.CharField(choices=[('direct_commit', 'Direct commit'), ('branch_pr', 'Feature branch + PR')], default='direct_commit', max_length=16)),
                ('auto_sync', models.BooleanField(default=True, help_text='Commit platform edits back to Git automatically.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_git_repositories', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='git_repositories', to='workspaces.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_repositories', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'git_repository',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GitSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('syncing', 'Syncing'), ('error', 'Error')], default='idle', max_length=16)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('last_synced_sha', models.CharField(blank=True, max_length=64)),
                ('last_pulled_at', models.DateTimeField(blank=True, null=True)),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to='git.gitrepository')),
            ],
            options={
                'db_table': 'git_sync_state',
            },
        ),
        migrations.CreateModel(
            name='GitCommitReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha', models.CharField(max_length=64)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('author_email', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(choices=[('import', 'Import (Git -> platform)'), ('export', 'Export (platform -> Git)')], max_length=16)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='git_commits', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='git.gitrepository')),
            ],
            options={
                'db_table': 'git_commit_reference',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['repository', '-created_at'], name='git_commit__reposit_9237a4_idx')],
            },
        ),
    ]
