# Generated by Django 5.2.17 on 2026-09-27 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0001_initial'),
        ('secrets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepository',
            name='secret',
            field=models.ForeignKey(blank=True, help_text='Optional Secret Vault credential used for this repository (overrides BRAINBOX_GIT_TOKEN). The secret must be owned by the user who created the repository and attached to its workspace/project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='git_repositories', to='secrets.secret'),
        ),
    ]
