# Generated by Django 5.2.17 on 2026-09-27 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0002_gitrepository_secret'),
        ('secrets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='git.gitrepository')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_credentials', to='secrets.secret')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'git_credential',
                'ordering': ['user'],
                'constraints': [models.UniqueConstraint(fields=('repository', 'user'), name='uniq_git_credential_per_user')],
            },
        ),
    ]
