# Generated by Django 5.2.17 on 2026-09-25 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('wikilink', 'Obsidian wikilink'), ('reference', 'Reference'), ('related', 'Related'), ('parent', 'Parent'), ('child', 'Child'), ('embed', 'Embed')], default='reference', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_links', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='resources.resource')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='resources.resource')),
            ],
            options={
                'db_table': 'links_resource_link',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'link_type'], name='links_resou_source__7cfa34_idx'), models.Index(fields=['target', 'link_type'], name='links_resou_target__a51f84_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'target', 'link_type'), name='uniq_resource_link')],
            },
        ),
    ]
