# Generated by Django 5.2.17 on 2026-10-07 06:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0007_documentcomment'),
        ('resources', '0003_alter_resource_resource_type'),
        ('workspaces', '0002_workspace_kind_owner_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('subject_key', models.CharField(db_index=True, max_length=255)),
                ('predicate', models.CharField(max_length=64)),
                ('object', models.CharField(blank=True, max_length=512)),
                ('assertion', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='workspaces.project')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='documents.document')),
                ('source_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='resources.resource')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'memory_fact',
                'ordering': ['subject_key', 'predicate'],
                'indexes': [models.Index(fields=['subject_key', 'predicate'], name='memory_fact_subject_d1396f_idx')],
            },
        ),
    ]
