# Generated by Django 5.2.17 on 2026-10-07 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
        ('resources', '0003_alter_resource_resource_type'),
        ('workspaces', '0002_workspace_kind_owner_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='origin',
            field=models.CharField(default='deterministic', help_text='How the fact was found: deterministic, llm or reflection.', max_length=16),
        ),
        migrations.CreateModel(
            name='MemoryAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('subject_key', models.CharField(db_index=True, max_length=255)),
                ('text', models.TextField()),
                ('confidence', models.FloatField(default=0.7)),
                ('origin', models.CharField(default='deterministic', max_length=16)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sources', models.ManyToManyField(related_name='memory_aggregates', to='resources.resource')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_aggregates', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'memory_aggregate',
                'ordering': ['subject_key'],
            },
        ),
    ]
