# Generated by Django 5.2.17 on 2026-10-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_fact_origin_memoryaggregate'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryaggregate',
            name='proof_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
