# Generated by Django 5.2.17 on 2026-09-25 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('secret_type', models.CharField(choices=[('password', 'Username / password'), ('api_key', 'API key'), ('bearer_token', 'Bearer token'), ('ssh_key', 'SSH key'), ('certificate', 'Certificate'), ('client_credentials', 'Client ID + secret'), ('json', 'JSON'), ('key_value', 'Key / value'), ('generic', 'Generic')], default='generic', max_length=32)),
                ('encrypted_payload', models.TextField()),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'secrets_secret',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SecretAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_secret_attachments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.project')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='secrets.secret')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'secrets_attachment',
            },
        ),
        migrations.AddConstraint(
            model_name='secret',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_owner_secret_name'),
        ),
        migrations.AddConstraint(
            model_name='secretattachment',
            constraint=models.UniqueConstraint(fields=('secret', 'workspace', 'project'), name='uniq_secret_attachment'),
        ),
    ]
