# Generated by Django 5.2.17 on 2026-09-25 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('resources', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='document', serialize=False, to='resources.resource')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=255)),
                ('path', models.CharField(help_text='Relative path under the documents dir', max_length=1024)),
                ('summary', models.TextField(blank=True)),
                ('mime_type', models.CharField(default='text/markdown', max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('experimental', 'Experimental'), ('approved', 'Approved'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('priority', models.IntegerField(default=0)),
                ('frontmatter', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('current_version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspaces.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'documents_document',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('content', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('change_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('restore', 'Restore'), ('import', 'Import'), ('ai', 'AI generated'), ('delete', 'Delete')], default='update', max_length=16)),
                ('source', models.CharField(choices=[('web', 'Web UI'), ('api', 'REST API'), ('mcp', 'MCP'), ('git', 'Git'), ('import', 'Import'), ('system', 'System')], default='web', max_length=16)),
                ('git_commit', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_versions', to='accounts.apikey')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_versions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'db_table': 'documents_document_version',
                'ordering': ['-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('workspace', 'path'), name='uniq_document_path_workspace'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project', 'path'), name='uniq_document_path_project'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='uniq_document_version'),
        ),
    ]
