# Generated by Django 5.2.17 on 2026-09-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Sablon: nem kerül a keresési indexbe, de új dokumentumok példányosíthatók belőle.'),
        ),
    ]
