# Generated by Django 5.2.17 on 2026-09-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'knowledge group', 'verbose_name_plural': 'knowledge groups'},
        ),
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'verbose_name': 'knowledge group membership', 'verbose_name_plural': 'knowledge group memberships'},
        ),
    ]
