# Generated by Django 5.2.17 on 2026-10-06 23:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0003_alter_resource_resource_type'),
        ('workspaces', '0002_workspace_kind_owner_project_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratorProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('duplicate', 'Exact duplicate'), ('stale', 'Stale (review due)')], max_length=32)),
                ('signature', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=512)),
                ('rationale', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('stale', 'No longer found')], db_index=True, default='open', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curator_decisions', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curator_proposals', to='resources.resource')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curator_proposals', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'curator_proposal',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'kind', 'signature'), name='uniq_curator_proposal')],
            },
        ),
    ]
