# Generated by Django 5.2.17 on 2026-09-25 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('resources', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingIndexState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('dimension', models.IntegerField(default=0)),
                ('backend', models.CharField(blank=True, max_length=64)),
                ('chunks_count', models.IntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('indexed', 'Indexed'), ('error', 'Error')], default='pending', max_length=16)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_state', to='documents.document')),
            ],
            options={
                'db_table': 'embeddings_index_state',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('token_count', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=16)),
                ('priority', models.IntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='resources.resource')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'embeddings_knowledge_chunk',
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['workspace', 'project'], name='embeddings__workspa_35a43a_idx'), models.Index(fields=['resource'], name='embeddings__resourc_f9c2d4_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='uniq_document_chunk_index')],
            },
        ),
    ]
