# Generated by Django 5.2.17 on 2026-09-25 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('resources', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('read', 'Read'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('search', 'Search'), ('follow_link', 'Follow link'), ('login', 'Login'), ('logout', 'Logout'), ('change_permission', 'Change permission'), ('create_api_key', 'Create API key'), ('revoke_api_key', 'Revoke API key'), ('use_secret', 'Use secret'), ('git_commit', 'Git commit'), ('git_pull', 'Git pull'), ('git_push', 'Git push'), ('mcp_request', 'MCP request')], db_index=True, max_length=32)),
                ('source', models.CharField(choices=[('web', 'Web UI'), ('api', 'REST API'), ('mcp', 'MCP'), ('git', 'Git'), ('system', 'System')], default='system', max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('denied', 'Denied')], default='success', max_length=16)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('git_commit', models.CharField(blank=True, max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='accounts.apikey')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workspaces.project')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='resources.resource')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'audit_event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', '-timestamp'], name='audit_event_action_1b99fa_idx')],
            },
        ),
    ]
