# Generated by Django 5.2.17 on 2026-10-04 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('resources', '0002_resource_no_takeover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The Resource of the project the event happened in. It points at the Resource and not at a Project row because an audit entry records where something happened at the time it happened: the UUID is the same one a Project row used to carry (Project.pk == its Resource id), so existing rows are untouched, and a project renamed into a plain folder - or deleted entirely - must not take history with it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resources.resource'),
        ),
    ]
