# Generated by Django 5.2.17 on 2026-10-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditevent_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('read', 'Read'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('search', 'Search'), ('follow_link', 'Follow link'), ('login', 'Login'), ('logout', 'Logout'), ('change_permission', 'Change permission'), ('create_api_key', 'Create API key'), ('revoke_api_key', 'Revoke API key'), ('use_secret', 'Use secret'), ('gateway_call', 'Gateway call'), ('git_commit', 'Git commit'), ('git_pull', 'Git pull'), ('git_push', 'Git push'), ('mcp_request', 'MCP request')], db_index=True, max_length=32),
        ),
    ]
