# Generated by Django 5.2.17 on 2026-09-25 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceACL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('user', 'User'), ('group', 'Group'), ('api_key', 'API key')], max_length=16)),
                ('subject_id', models.UUIDField()),
                ('permission', models.CharField(choices=[('read', 'Read'), ('use', 'Use'), ('write', 'Write'), ('delete', 'Delete'), ('admin', 'Admin')], max_length=16)),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='allow', max_length=8)),
                ('inherit', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_acl_entries', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl_entries', to='resources.resource')),
            ],
            options={
                'db_table': 'permissions_resource_acl',
                'ordering': ['resource', 'subject_type', 'permission'],
                'indexes': [models.Index(fields=['subject_type', 'subject_id'], name='permissions_subject_5e2ab0_idx')],
                'constraints': [models.UniqueConstraint(fields=('resource', 'subject_type', 'subject_id', 'permission'), name='uniq_resource_acl_entry')],
            },
        ),
    ]
